---
- name: Copy SYNCPROV_MOD ldif
  template: >
    src=syncprov_mod.ldif.j2
    dest=/tmp/syncprov_mod.ldif
  when: openkrb_servers_ha == True

- name: Check if syncprov_mod already exists
  shell: echo `ldapsearch -Y EXTERNAL -H ldapi:/// -b "cn=module{0},cn=config" -s sub "objectclass=*"`
  register: checksyncprovmod
  check_mode: no
  ignore_errors: True
  changed_when: False

- name: Deploy syncprov_mod
  command: ldapadd -Y EXTERNAL -H ldapi:/// -f /tmp/syncprov_mod.ldif
  failed_when: checksyncprovmod.stdout.find("syncprov.la") == 0 and openkrb_servers_ha == False

- name: SYNCPROV (CentOS/Redhat)
  block:
    - name: Copy SYNCPROV ldif
      template: >
        src=syncprov.ldif.j2
        dest=/tmp/syncprov.ldif
      when: openkrb_servers_ha == True

    - name: Check if syncprov already exists
      command: ldapsearch -Y EXTERNAL -H ldapi:/// -b "cn=config" -s sub "objectclass=*"
      register: checksyncprov
      check_mode: no
      ignore_errors: True
      changed_when: False

    - name: Deploy syncprov
      command: ldapadd -Y EXTERNAL -H ldapi:/// -f /tmp/syncprov.ldif
      when: checksyncprov.stdout.find("syncprov,olcDatabase={2}hdb,cn=config") == -1 and openkrb_servers_ha == True

    - name: Copy RP.ldif
      template: >
        src=rp.ldif.j2
        dest=/tmp/rp.ldif
      when: openkrb_servers_ha == True

    - name: Check if rp already exists
      command: echo `ldapsearch -Y EXTERNAL -H ldapi:/// -b "cn=config" -s sub "objectclass=*"`
      register: checkrp
      check_mode: no
      ignore_errors: True
      changed_when: False

    - name: Deploy rp
      command: ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/rp.ldif
      failed_when: checkrp.stdout.find("olcSyncRepl") == 0 and openkrb_servers_ha == False
  when: (ansible_distribution != 'Rocky') and (ansible_distribution != 'AlmaLinux')

- name: SYNCPROV (Rocky)
  block:
    - name: Copy SYNCPROV ldif
      template: >
        src=rhel8/syncprov.ldif.j2
        dest=/tmp/syncprov.ldif
      when: openkrb_servers_ha == True

    - name: Check if syncprov already exists
      command: ldapsearch -Y EXTERNAL -H ldapi:/// -b "cn=config" -s sub "objectclass=*"
      register: checksyncprov
      check_mode: no
      ignore_errors: True
      changed_when: False

    - name: Deploy syncprov
      command: ldapadd -Y EXTERNAL -H ldapi:/// -f /tmp/syncprov.ldif
      when: checksyncprov.stdout.find("syncprov,olcDatabase={2}mdb,cn=config") == -1 and openkrb_servers_ha == True

    - name: Copy RP.ldif
      template: >
        src=rhel8/rp.ldif.j2
        dest=/tmp/rp.ldif
      when: openkrb_servers_ha == True

    - name: Check if rp already exists
      command: echo `ldapsearch -Y EXTERNAL -H ldapi:/// -b "cn=config" -s sub "objectclass=*"`
      register: checkrp
      check_mode: no
      ignore_errors: True
      changed_when: False

    - name: Deploy rp
      command: ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/rp.ldif
      failed_when: checkrp.stdout.find("olcSyncRepl") == 0 and openkrb_servers_ha == False
  when: ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux'

- name: Restart service slapd
  systemd:
    state: restarted
    name: slapd
  register: restart_slapd
  until: restart_slapd.status.Result == "success"
  retries: 10
  delay: 20

- name: Sleep
  command: sleep 10