---
# Preinstall
- import_tasks: pre_install.yml
#
# OpenLDAP install
- import_tasks: deploy_openldap.yml

# Enable multi masters for OpenLDAP
- import_tasks: deploy_openldap_multimaster.yml

# Create users
- import_tasks: create_users.yml

# Kerberos install
- import_tasks: deploy_kerberos.yml

# # Securize installation
# - import_tasks: securize.yml
